version: '3'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  graphql:
    hostname: localhost
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CONCURRENCY=2
    ports:
      - "4000:4000"
